package hib;
// Generated Dec 17, 2019 6:40:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.sql.Timestamp;

/**
 * HistoryId generated by hbm2java
 */
public class HistoryId implements java.io.Serializable {

	private int userid;
	private int mid;
	private Timestamp viewtime;

	public HistoryId() {
	}

	public HistoryId(int userid, int mid, Timestamp viewtime) {
		this.userid = userid;
		this.mid = mid;
		this.viewtime = viewtime;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public Timestamp getViewtime() {
		return this.viewtime;
	}

	public void setViewtime(Timestamp viewtime) {
		this.viewtime = viewtime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HistoryId))
			return false;
		HistoryId castOther = (HistoryId) other;

		return (this.getUserid() == castOther.getUserid()) && (this.getMid() == castOther.getMid())
				&& ((this.getViewtime() == castOther.getViewtime()) || (this.getViewtime() != null
						&& castOther.getViewtime() != null && this.getViewtime().equals(castOther.getViewtime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getMid();
		result = 37 * result + (getViewtime() == null ? 0 : this.getViewtime().hashCode());
		return result;
	}

}
